/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseRouteImport } from './routes/analise'
import { Route as CurriculoRouteImport } from './routes/curriculo'
import { Route as CurriculoGeradoRouteImport } from './routes/curriculo-gerado'
import { Route as NovaVagaRouteImport } from './routes/nova-vaga'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRoute = AnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoRoute = CurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculoGeradoRoute = CurriculoGeradoRouteImport.update({
  id: '/curriculo-gerado',
  path: '/curriculo-gerado',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaVagaRoute = NovaVagaRouteImport.update({
  id: '/nova-vaga',
  path: '/nova-vaga',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/curriculo': typeof CurriculoRoute
  '/curriculo-gerado': typeof CurriculoGeradoRoute
  '/nova-vaga': typeof NovaVagaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/curriculo': typeof CurriculoRoute
  '/curriculo-gerado': typeof CurriculoGeradoRoute
  '/nova-vaga': typeof NovaVagaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise': typeof AnaliseRoute
  '/curriculo': typeof CurriculoRoute
  '/curriculo-gerado': typeof CurriculoGeradoRoute
  '/nova-vaga': typeof NovaVagaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analise' | '/curriculo' | '/curriculo-gerado' | '/nova-vaga'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analise' | '/curriculo' | '/curriculo-gerado' | '/nova-vaga'
  id:
    | '__root__'
    | '/'
    | '/analise'
    | '/curriculo'
    | '/curriculo-gerado'
    | '/nova-vaga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseRoute: typeof AnaliseRoute
  CurriculoRoute: typeof CurriculoRoute
  CurriculoGeradoRoute: typeof CurriculoGeradoRoute
  NovaVagaRoute: typeof NovaVagaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise': {
      id: '/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo': {
      id: '/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof CurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculo-gerado': {
      id: '/curriculo-gerado'
      path: '/curriculo-gerado'
      fullPath: '/curriculo-gerado'
      preLoaderRoute: typeof CurriculoGeradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-vaga': {
      id: '/nova-vaga'
      path: '/nova-vaga'
      fullPath: '/nova-vaga'
      preLoaderRoute: typeof NovaVagaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseRoute: AnaliseRoute,
  CurriculoRoute: CurriculoRoute,
  CurriculoGeradoRoute: CurriculoGeradoRoute,
  NovaVagaRoute: NovaVagaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
