/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnaliseRouteImport } from './routes/_authenticated/analise'
import { Route as AuthenticatedCurriculoRouteImport } from './routes/_authenticated/curriculo'
import { Route as AuthenticatedCurriculoGeradoRouteImport } from './routes/_authenticated/curriculo-gerado'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedNovaVagaRouteImport } from './routes/_authenticated/nova-vaga'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnaliseRoute = AuthenticatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculoRoute = AuthenticatedCurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCurriculoGeradoRoute =
  AuthenticatedCurriculoGeradoRouteImport.update({
    id: '/curriculo-gerado',
    path: '/curriculo-gerado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaVagaRoute = AuthenticatedNovaVagaRouteImport.update({
  id: '/nova-vaga',
  path: '/nova-vaga',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/curriculo': typeof AuthenticatedCurriculoRoute
  '/curriculo-gerado': typeof AuthenticatedCurriculoGeradoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/nova-vaga': typeof AuthenticatedNovaVagaRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/curriculo': typeof AuthenticatedCurriculoRoute
  '/curriculo-gerado': typeof AuthenticatedCurriculoGeradoRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/nova-vaga': typeof AuthenticatedNovaVagaRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/analise': typeof AuthenticatedAnaliseRoute
  '/_authenticated/curriculo': typeof AuthenticatedCurriculoRoute
  '/_authenticated/curriculo-gerado': typeof AuthenticatedCurriculoGeradoRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/nova-vaga': typeof AuthenticatedNovaVagaRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/analise'
    | '/curriculo'
    | '/curriculo-gerado'
    | '/historico'
    | '/nova-vaga'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/redefinir-senha'
    | '/analise'
    | '/curriculo'
    | '/curriculo-gerado'
    | '/historico'
    | '/nova-vaga'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/analise'
    | '/_authenticated/curriculo'
    | '/_authenticated/curriculo-gerado'
    | '/_authenticated/historico'
    | '/_authenticated/nova-vaga'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise': {
      id: '/_authenticated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AuthenticatedAnaliseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculo': {
      id: '/_authenticated/curriculo'
      path: '/curriculo'
      fullPath: '/curriculo'
      preLoaderRoute: typeof AuthenticatedCurriculoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curriculo-gerado': {
      id: '/_authenticated/curriculo-gerado'
      path: '/curriculo-gerado'
      fullPath: '/curriculo-gerado'
      preLoaderRoute: typeof AuthenticatedCurriculoGeradoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-vaga': {
      id: '/_authenticated/nova-vaga'
      path: '/nova-vaga'
      fullPath: '/nova-vaga'
      preLoaderRoute: typeof AuthenticatedNovaVagaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnaliseRoute: typeof AuthenticatedAnaliseRoute
  AuthenticatedCurriculoRoute: typeof AuthenticatedCurriculoRoute
  AuthenticatedCurriculoGeradoRoute: typeof AuthenticatedCurriculoGeradoRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedNovaVagaRoute: typeof AuthenticatedNovaVagaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnaliseRoute: AuthenticatedAnaliseRoute,
  AuthenticatedCurriculoRoute: AuthenticatedCurriculoRoute,
  AuthenticatedCurriculoGeradoRoute: AuthenticatedCurriculoGeradoRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedNovaVagaRoute: AuthenticatedNovaVagaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
